{
 "title": "nvitop-exporter",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU Utilization",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "host_cpu_percent_Percentage", "legendFormat": "{{hostname}} CPU (%)" }
   ]
  },
  {
   "title": "GPU Utilization",
   "type": "gauge",
   "gridPos": { "h": 18, "w": 11, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "gpu_utilization_Percentage", "legendFormat": "{{hostname}} GPU {{index}} (%)" }
   ]
  },
  {
   "title": "GPU Memory",
   "type": "gauge",
   "gridPos": { "h": 18, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "gpu_memory_percent_Percentage", "legendFormat": "{{hostname}} GPU {{index}} (%)" }
   ]
  },
  {
   "title": "Host Virtual Memory",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "host_virtual_memory_percent_Percentage",
     "legendFormat": "{{hostname}} MEM (%)"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "host_cpu_percent_Percentage", "legendFormat": "{{hostname}}" }
   ]
  },
  {
   "title": "CPU Load Average",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "host_load_average_1m_Percentage",
     "legendFormat": "{{hostname}} (1m)"
    },
    {
     "expr": "host_load_average_5m_Percentage",
     "legendFormat": "{{hostname}} (5m)"
    },
    {
     "expr": "host_load_average_15m_Percentage",
     "legendFormat": "{{hostname}} (15m)"
    }
   ]
  },
  {
   "title": "Host Virtual Memory",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    { "expr": "host_virtual_memory_used_MiB", "legendFormat": "{{hostname}}" }
   ]
  },
  {
   "title": "Host Swap Memory",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    { "expr": "host_swap_memory_used_MiB", "legendFormat": "{{hostname}}" }
   ]
  },
  {
   "title": "Host Network I/O",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "MiBs" } },
   "targets": [
    {
     "expr": "sum by(hostname) (rate(host_net_io_rx_data_MiB[$__rate_interval]))",
     "legendFormat": "{{hostname}} RX"
    },
    {
     "expr": "sum by(hostname) (rate(host_net_io_tx_data_MiB[$__rate_interval]))",
     "legendFormat": "{{hostname}} TX"
    }
   ]
  },
  {
   "title": "Host Disk I/O",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "MiBs" } },
   "targets": [
    {
     "expr": "sum by(hostname) (rate(host_disk_io_read_data_MiB[$__rate_interval]))",
     "legendFormat": "{{hostname}} Read"
    },
    {
     "expr": "sum by(hostname) (rate(host_disk_io_write_data_MiB[$__rate_interval]))",
     "legendFormat": "{{hostname}} Write"
    }
   ]
  },
  {
   "title": "GPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by(hostname) (gpu_utilization_Percentage)",
     "legendFormat": "{{hostname}} Average"
    },
    { "expr": "gpu_utilization_Percentage", "legendFormat": "{{hostname}} GPU {{index}}" }
   ]
  },
  {
   "title": "GPU Memory",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "avg by(hostname) (gpu_memory_used_MiB)",
     "legendFormat": "{{hostname}} Average"
    },
    { "expr": "gpu_memory_used_MiB", "legendFormat": "{{hostname}} GPU {{index}}" }
   ]
  },
  {
   "title": "GPU PCIe RX Throughput",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "MiBs" } },
   "targets": [
    {
     "expr": "avg by(hostname) (gpu_pcie_rx_throughput_MiBps)",
     "legendFormat": "{{hostname}} Average"
    },
    { "expr": "gpu_pcie_rx_throughput_MiBps", "legendFormat": "{{hostname}} GPU {{index}}" }
   ]
  },
  {
   "title": "GPU PCIe TX Throughput",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "MiBs" } },
   "targets": [
    {
     "expr": "avg by(hostname) (gpu_pcie_rx_throughput_MiBps)",
     "legendFormat": "{{hostname}} Average"
    },
    { "expr": "gpu_pcie_rx_throughput_MiBps", "legendFormat": "{{hostname}} GPU {{index}}" }
   ]
  },
  {
   "title": "GPU NVLink RX Throughput",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "MiBs" } },
   "targets": [
    {
     "expr": "avg by(hostname) (gpu_nvlink_total_rx_throughput_MiBps)",
     "legendFormat": "{{hostname}} Average"
    },
    {
     "expr": "gpu_nvlink_total_rx_throughput_MiBps",
     "legendFormat": "{{hostname}} GPU {{index}}"
    }
   ]
  },
  {
   "title": "GPU NVLink TX Throughput",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "MiBs" } },
   "targets": [
    {
     "expr": "avg by(hostname) (gpu_nvlink_total_tx_throughput_MiBps)",
     "legendFormat": "{{hostname}} Average"
    },
    {
     "expr": "gpu_nvlink_total_tx_throughput_MiBps",
     "legendFormat": "{{hostname}} GPU {{index}}"
    }
   ]
  },
  {
   "title": "GPU Power Usage",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "avg by(hostname) (gpu_power_usage_W)",
     "legendFormat": "{{hostname}} Average"
    },
    { "expr": "gpu_power_usage_W", "legendFormat": "{{hostname}} GPU {{index}}" }
   ]
  },
  {
   "title": "GPU Temperature",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg by(hostname) (gpu_temperature_C)",
     "legendFormat": "{{hostname}} Average"
    },
    { "expr": "gpu_temperature_C", "legendFormat": "{{hostname}} GPU {{index}}" }
   ]
  }
 ]
}